#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the arrayManipulation function below.
def arrayManipulation(n, queries):
    list = [0]*(n+1)
    for i in (queries):
        x, y, incr = i[0],i[1],i[2]
        list[x-1] += incr
        if((y)<=len(list)): list[y] -= incr;
    maxi = x = 0
    for i in list:
        x=x+i;
        if(maxi<x): maxi=x;
    return maxi


if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    nm = input().split()

    n = int(nm[0])

    m = int(nm[1])

    queries = []

    for _ in range(m):
     queries.append(list(map(int, input().rstrip().split())))

    result = arrayManipulation(n, queries)
    fptr.write(str(result) + '\n')

    fptr.close()
